version: '3.1'

services:
  prometheus-server:
    image: prom/prometheus
    container_name: prometheus-server
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: '104'
    ports:
      - 3001:3000
    #volumes:
     # - ./grafana:/var/lib/grafana
    restart: unless-stopped