global:
  scrape_interval: 4s
  evaluation_interval: 4s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    # scheme: https
    static_configs:
      - targets: ['192.168.1.12:9100']